# Generated by Django 5.0.3 on 2024-03-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duck',
            fields=[
                ('fileID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('food', models.CharField(max_length=10)),
                ('credit', models.IntegerField()),
            ],
        ),
    ]
